[package]
name = "webrtc_proxy_client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
enaia_client.path = "../enaia_client"
rusty_enet = { git = "https://github.com/jabuwu/rusty_enet", rev = "dca889b30b350c9ca63f9a0b67d46328cfda4f37" }
web-time = "0.2.3"
