[package]
name = "enaia_server"
version = "0.1.0"
edition = "2021"

[dependencies]
naia-server-socket = "0.20.0"
naia-socket-shared = "0.20.0"
rusty_enet = { git = "https://github.com/jabuwu/rusty_enet", rev = "dca889b30b350c9ca63f9a0b67d46328cfda4f37" }
